### ISSUE TITLE
timeout appears not to be enforcing

### ISSUE THREAD

**Issue by merlinm** [hasankhan/sql-cli#14]
No matter what I pass for timeout option, long running queries appear to cancel in 15 seconds.  

mmoncure@mernix2 08:43 AM ~$ mssql --version
0.4.6

mmoncure@mernix2 08:41 AM ~$ time mssql -f csv -t 1000000 -q "select * from property" > /dev/null
Error: Timeout: Request failed to complete in 15000ms

real	0m15.916s
user	0m15.720s
sys	0m0.313s

**Comment by erick2red** [comment]
@merlinm The error you're seeing is because of the request, you should set **-T** request timeout instead of **-t** which appears to be connection timeout.
