### ISSUE TITLE
Poor performance and excessive memory consumption when streaming large results

### ISSUE THREAD

**Issue by merlinm** [hasankhan/sql-cli#15]
mmoncure@mernix2 08:41 AM ~$ time mssql  -f csv -t 1000000 -q "select \* from property" > /dev/null
Error: Timeout: Request failed to complete in 15000ms

real    0m15.916s
user    0m15.720s
sys 0m0.313s

This query times out but 15 seconds in the memory consumption is around 700mb.  The results should be buffered and streamed out rather than collected in memory for display.  Not doing this makes the cli tool problematic for large .csv extractions which I'm currently using sqsh for -- would very much like to switch to this tool but it must be able to handle those kinds of workloads.

**Comment by hasankhan** [comment]
i'll address this one soon

**Comment by hasankhan** [comment]
Please get version 0.4.10
