### ISSUE TITLE
Not able to load settings from config

### ISSUE THREAD

**Issue by tkleijkers** [hasankhan/sql-cli#16]
I try to connect using a config file with the option -c. I tried with several formats: { user: 'user', pass: 'pass' } etc, but I cannot get it working. Is this functionality available? If yes, please add some documentation of the format of the config file.

**Comment by hasankhan** [comment]
Config file is a json file
with following format

{
            "user": "usernamehere",
            "pass": "passwordhere",
            "server": "server address",
            "database": "db name",
}

See the options file for details: https://github.com/hasankhan/sql-cli/blob/master/lib/options.js
