### ISSUE TITLE
Azure CLI Integration Fails

### ISSUE THREAD

**Issue by nysky1** [hasankhan/sql-cli#17]
I was thrilled to find this today.  But the command:
"azure mobile sqldb" : error 'sqldb' is not an azure command.

Running 0.4.5 on OSX with Azure CLI 0.9.8

Just a quick answer if this is a dead-end or not would be incredibly helpful.

Thanks!

**Comment by hasankhan** [comment]
Did you globally install sql-cli before trying to run this command?

**Comment by nysky1** [comment]
Yes, I did use the -g flag

J.

**Comment by hasankhan** [comment]
It's possible they have updated the way plugins work. You can take your database connection parameters and use them directly against sql-ci instead of invoking it via azure cli.

**Comment by hasankhan** [comment]
integration removed.
