### ISSUE TITLE
Support multi line statements 

### ISSUE THREAD

**Issue by steve-chavez** [hasankhan/sql-cli#18]
Statement in one line like:

```sql
CREATE TABLE persons ( id INT IDENTITY(1,1), full_name VARCHAR(200) );
```
Work fine, but if I do :

```sql
CREATE TABLE persons ( 
  id INT IDENTITY(1,1), 
  full_name VARCHAR(200) 
);
```

It gives me several ```Error: Incorrect syntax```, with the .run command I can achieve this if I save that as a file but is inconvenient for just testing some statements.

**Comment by hasankhan** [comment]
multiline statements are already supported, please end your lines with backslash if you wish to continue to the next line
