### ISSUE TITLE
information_schema queries don't work for case-sensitive databases

### ISSUE THREAD

**Issue by frstie** [hasankhan/sql-cli#19]
The queries .tables and .schema use to get meta information about columns etc both use lower case 'information_schema'  and column names, when in fact these are all in uppercase in SQL Server.

This doesn't affect databases that are configured as case-insensitive (which is the default I believe)

If I get a spare minute I'll submit a pull request but it should just be a matter of changing the case of those table and column names in the queries.

**Comment by hasankhan** [comment]
Fixed
