### ISSUE TITLE
Invalid object name between SQL statements

### ISSUE THREAD

**Issue by dbarros** [hasankhan/sql-cli#22]
I seems that if I don't run a SQL statement within a minute (or so) between one another, the connection to the database is lost? 

For example: I connect to a server, run `use [database_name]`. Then I run some `select` statement. Fine, results are returned. But if I don't run another command very shortly afterwards, I start getting the error: `Error: Invalid object name 'company'.` In this case, where `company` is the table name.

I need to run `use [database_name]` again for it to continue to work.

I am on macOS, connecting to a MS SQL Server 2012 instance.

**Comment by hasankhan** [comment]
Which version of the client are you using?

**Comment by dbarros** [comment]
@hasankhan I'm using 0.4.7, on macOS 10.12.

**Comment by hasankhan** [comment]
i'll take a look

**Comment by hasankhan** [comment]
I wasn't able to reproduce the problem, can you try the latest code in the repo? Just git clone, switch to dev branch and do a `npm install -g`

**Comment by dbarros** [comment]
@hasankhan Thanks, I'll try you suggestion.

**Comment by dbarros** [comment]
@hasankhan I think it just has to do with node-mssql having a very short connection timeout default setting of 15 seconds. That's why the error occurs.

I'm just going to set the default using the env variable SQLCLI_TIMEOUT as used in options.js
