### ISSUE TITLE
.help throws error writer.write is not a function - tried on both macOS and Ubuntu

### ISSUE THREAD

**Issue by jonelr** [hasankhan/sql-cli#26]
TypeError: writer.write is not a function
    at HelpCommand.run (/usr/lib/node_modules/sql-cli/lib/commands/help.js:22:20)
    at Invoker.run (/usr/lib/node_modules/sql-cli/lib/commands/invoker.js:21:28)
    at SqlCli._runCommand (/usr/lib/node_modules/sql-cli/lib/cli.js:108:26)
    at emitOne (events.js:96:13)
    at Prompt.emit (events.js:188:7)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:239:10)
    at Interface._line (readline.js:585:8)
    at Interface._ttyWrite (readline.js:862:14)

**Comment by basitanwer** [comment]
Couldn't produce it on Linux/Ubuntu

## Linux Version ##

**Distributor ID:** Ubuntu
**Description:**    Ubuntu 16.04.1 LTS
**Release:**        16.04
**Codename:**       xenial

``` bash
azureuser@hh-db:~/github/sql-cli$ mssql -h

  Usage: mssql [options]

  Options:

    -h, --help                      output usage information
    -V, --version                   output the version number
    -s, --server <server>           Server to conect to
    -u, --user <user>               User name to use for authentication
    -p, --pass <pass>               Password to use for authentication
    -o, --port <port>               Port to connect to
    -t, --timeout <timeout>         Connection timeout in ms
    -T, --requestTimeout <timeout>  Request timeout in ms
    -d, --database <database>       Database to connect to
    -q, --query <query>             The query to execute
    -v, --tdsVersion <tdsVersion>   Version of tds protocol to use [7_4, 7_2, 7_3_A, 7_3_B, 7_4]
    -e, --encrypt                   Enable encryption
    -f, --format <format>           The format of output [table, csv, xml, json]
    -c, --config <path>             Read connection information from config file
```

**Comment by hasankhan** [comment]
Fixed it, thanks for reporting the issue. You can grab version 0.4.11 for fix.
