### ISSUE TITLE
Password Prompt

### ISSUE THREAD

**Issue by eddyfan** [hasankhan/sql-cli#28]
By typing "mssql -S MyServerIP -U SA -p", I expect to see a password prompt. Instead, I am asked to type in the password in clear text as a parameter of -p. Is making "mssql -S MyServerIP -U SA -p" to prompt for password on the road map for sql-cli? Thank you.

**Comment by hasankhan** [comment]
i'll take a look at this.

**Comment by hasankhan** [comment]
Fixed, please get the 0.4.14 release.

**Comment by eddyfan** [comment]
Thanks. That worked.
