### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by super1-chen** [hasankhan/sql-cli#29]
I installed sql-cli as the tutorial indication at the website[https://www.npmjs.com/package/sql-cli](https://www.npmjs.com/package/sql-cli). After finished install, I run the command  "mssql -h", the terminal shows information as bellow. Could you give me some suggestions on how to solve this problem thx!

![screen shot 2016-12-27 at 11 57 37 pm](https://cloud.githubusercontent.com/assets/11963227/21503177/4e4d5312-cc90-11e6-904e-00db46f831b1.png)

**Comment by super1-chen** [comment]
I installed the sql-cli just run command "npm install -g sql-cli"

**Comment by hasankhan** [comment]
Please install latest version of node
