### ISSUE TITLE
Timeout not observed

### ISSUE THREAD

**Issue by richardson-marc** [hasankhan/sql-cli#34]
sql-cli does not seem to observe the timeout setting on the command line.  Commands still timeout after 15000ms, even when using a different timeout value

mssql -u sa -p ThisIsTheP@ssw0rd -t 25000
Connecting to localhost...done

sql-cli version 0.4.14
Enter ".help" for usage hints.
mssql> create database NewDatabase

mssql>
mssql> Error: Timeout: Request failed to complete in 15000ms

**Comment by hasankhan** [comment]
There are two timeout parameters, one is for connection and the other is for request. Have you tried the one with capital 'T'?
