### ISSUE TITLE
Execute Script from CMD Line / Pipe

### ISSUE THREAD

**Issue by egandro** [hasankhan/sql-cli#36]
Hi,

this is a very very nice Programm! I love it.

I have two questions. Is it possible:

1) To execude a script from CMD line?

$ mssql -p foo -e myscript.sql

2) From Pipe

$ echo "Select @@VERSION" | mssql -p foo

Thank you!

**Comment by hasankhan** [comment]
you can use the "-q" switch to run a query directly
you can use the "-q" with ".run" command to load a script file
you can pipe output to a file but piping input doesn't work currently

**Comment by egandro** [comment]
Thank you a lot :)

**Comment by hasankhan** [comment]
Pipe input works in version 0.5.2, give it a try.

**Comment by VictorPulzz** [comment]
@hasankhan Hello can you help me pls I tryed this command inside docker container:
```
mssql -s localhost -u sa -p asdasdasd -d master -q ".run /tmp/scripts/setup.sql asdasd"
```
But got this
```
error: ENOENT: no such file or directory, open '/tmp/scripts/setup.sql
```

**Comment by hasankhan** [comment]
I'm not actively working on the project. Please feel free to fork it and debug what is going on.
