### ISSUE TITLE
Can't "CREATE DATABASE" through Jenkins in v0.5.1

### ISSUE THREAD

**Issue by mtrippled** [hasankhan/sql-cli#39]
When executing from Jenkins to a remote build host, sql-cli silently fails to execute "CREATE DATABASE" commands on v0.5.1. This is not a problem either on v0.5.0, 0.4.14, or assumedly previous.

The jenkins build slave executing this is Ubuntu 16.04 LTS. node v6.9.0, npm 3.10.8.

Using npm package mssql@3.3.0.

Example command line that fails silently:
node_modules/.bin/mssql -s <somehost> -u <adminuser> -p <adminpw> -d master -q 'create database foo;'

This succeeds from the command line and when sshing in to the same host & user and executing the command from the ssh command line. It only fails when launched from Jenkins.

**Comment by hasankhan** [comment]
I'll fix this tonight. Please use v0.5 for now

**Comment by hasankhan** [comment]
Please try out 0.5.2, this should be resolved now

**Comment by mtrippled** [comment]
👍
