### ISSUE TITLE
Feature: ENV variables 

### ISSUE THREAD

**Issue by srhopkins** [hasankhan/sql-cli#51]
It would be nice to be able to set login details via env variables e.g.

```
export MSSQL_SERVER=my.sql.server
export MSSQL_PORT=1433
export MSSQL_USER=username
export MSSQL_PASS=password
... etc ... 
```

Thanks for the app its very helpful!

**Comment by hasankhan** [comment]
This feature is already implemented.

**Comment by srhopkins** [comment]
Excellent, can you point me to the variable names it's looking for. I tried doing a few searches on the repo and I am not able to locate this information.

**Comment by hasankhan** [comment]
https://github.com/hasankhan/sql-cli/blob/master/lib/options.js#L73

SQLCLI_USER, SQLCLI_PASSWORD, SQLCLI_SERVER, SQLCLI_DATABASE, SQLCLI_PORT, SQLCLI_TIMEOUT, SQLCLI_REQUEST_TIMEOUT, SQLCLI_TDSVERSION, SQLCLI_ENCRYPT
