### ISSUE TITLE
"env: node\r: No such file or directory" issue

### ISSUE THREAD

**Issue by Harrisonbro** [hasankhan/sql-cli#7]
On version 0.4.1 and 0.4.0 I'm getting an error: `env: node\r: No such file or directory`

It doesn't show the same error if I instead install 0.3.0 or 0.3.1. 

Currently running Node v0.12.0 and NPM v2.5.1 on Mac OS X Yosemite.

Let me know if there is any debugging I can help with. Not really sure myself what this error means...!

**Comment by hasankhan** [comment]
You get this error while installation of the package or execution of the CLI?

**Comment by Harrisonbro** [comment]
Only on execution. It seems to install OK.

**Comment by Harrisonbro** [comment]
For reference, here's the output from installing 0.4.1: http://pastebin.com/WNirsd9k
And for 0.3.1: http://pastebin.com/qj3bMujT

**Comment by hasankhan** [comment]
Can you run nodejs by typing "node" in command line? Installing the package should create this script in your path https://github.com/hasankhan/sql-cli/blob/master/bin/mssql which executes the CLI using node.

**Comment by Harrisonbro** [comment]
Yes I appear to be able to. Running `node` shows me the node prompt.

Note that running `which mssql` shows `/usr/local/bin/mssql`

**Comment by javajenks** [comment]
Same error for me (yosemite, / node 0.10.35 / npm 1.4.28) . I can run it fine doing the following though 
`node /usr/local/bin/mssql `

**Comment by jvstein** [comment]
I just hit the same problem. Removing the carriage return in the `mssql` script resolved the problem for me.

`dos2unix mssql`

**Comment by hasankhan** [comment]
Fixed in 0.4.2 release

**Comment by chicagogrooves** [comment]
@hasankhan - I observed this behavior on a Mac with the 0.4.3 release, that's how I found this page.

**Comment by hasankhan** [comment]
@chicagogrooves unfortunately my gitattributes file was not correctly configured and last release again caused the CRLF ending to be committed and published. Can you try the 0.4.4 release? Thanks
