### ISSUE TITLE
Request timeout not configurable

### ISSUE THREAD

**Issue by jvstein** [hasankhan/sql-cli#8]
The `-t` parameter doesn't set the requestTimeout property in mssql. It looks like that functionality was added in [version 0.6.0](https://github.com/patriksimek/node-mssql/blob/master/src/tedious.coffee#L190).

As a result, longer queries give me this error:
```
Error: Timeout: Request failed to complete in 15000ms
```

**Comment by hasankhan** [comment]
Do you mind fixing this and sending a pull request?

**Comment by jvstein** [comment]
Unfortunately, I have zero experience programming with node/coffeescript. I only dove in far enough to get my installed version hacked up and working for my purposes.

If you have some basic build/testing instructions (that will grab dependencies, etc) for this project, then I can take a stab at it.

**Comment by hasankhan** [comment]
1. install nodejs
2. clone the repo
3. update the mssql dependency in package.json
4. do an npm install on the repository root

See if the timeout is taking effect now, if so commit your changes and push them to your fork and send a pull request.
